name: test

on: [push]

jobs:

  freebsd-vm_0:
    # https://github.com/marketplace/actions/checkout
    # https://github.com/marketplace/actions/freebsd-vm
    # https://github.com/vmactions/freebsd-vm
    runs-on: ubuntu-latest
    name: run tests on FreeBSD 0
    steps:
    - uses: actions/checkout@v4
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        run: |
          env
          echo $SHELL
          set -e -x
          pwd
          ls -lah
          whoami
          freebsd-version
          mkdir foo
          mkdir foo
          ls

  freebsd-vm_1:
    # https://github.com/marketplace/actions/checkout
    # https://github.com/marketplace/actions/freebsd-vm
    # https://github.com/vmactions/freebsd-vm
    runs-on: ubuntu-latest
    name: run tests on FreeBSD 1
    steps:
    - uses: actions/checkout@v4
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v1
      with:
        run: |
          env
          echo $SHELL
          pwd
          ls -lah
          whoami
          freebsd-version
          mkdir foo
          mkdir foo
          ls

  freebsd-vm_2:
    # https://github.com/marketplace/actions/checkout
    # https://github.com/marketplace/actions/freebsd-vm
    # https://github.com/vmactions/freebsd-vm
    runs-on: ubuntu-latest
    name: run tests on FreeBSD 2
    steps:
    - uses: actions/checkout@v4
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v1
      with:
        run: |
          env
          echo $SHELL
          set -x
          pwd
          ls -lah
          whoami
          freebsd-version
          mkdir foo
          mkdir foo
          ls
