name: test

on: [push]

jobs:

  freebsd-vm_0:
    # https://github.com/marketplace/actions/checkout
    # https://github.com/marketplace/actions/freebsd-vm
    # https://github.com/vmactions/freebsd-vm
    runs-on: ubuntu-latest
    name: run tests on FreeBSD 0 (usesh true and set e x)
    steps:
    - uses: actions/checkout@v4
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v1.2.0
      with:
        usesh: true
        run: |
          set -e -x
          echo "SHELL: $0"
          ps -p $$
          pwd
          whoami
          freebsd-version
          mkdir foo
          mkdir foo
          ls -lah

  freebsd-vm_1:
    # https://github.com/marketplace/actions/checkout
    # https://github.com/marketplace/actions/freebsd-vm
    # https://github.com/vmactions/freebsd-vm
    runs-on: ubuntu-latest
    name: run tests on FreeBSD 1 (default)
    steps:
    - uses: actions/checkout@v4
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v1.2.0
      with:
        run: |
          echo "SHELL: $0"
          ps -p $$
          pwd
          whoami
          freebsd-version
          mkdir foo
          mkdir foo
          ls -lah

  freebsd-vm_2:
    # https://github.com/marketplace/actions/checkout
    # https://github.com/marketplace/actions/freebsd-vm
    # https://github.com/vmactions/freebsd-vm
    runs-on: ubuntu-latest
    name: run tests on FreeBSD 2 (default and set x)
    steps:
    - uses: actions/checkout@v4
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v1.2.0
      with:
        run: |
          set -x
          echo "SHELL: $0"
          ps -p $$
          pwd
          whoami
          freebsd-version
          mkdir foo
          mkdir foo
          ls -lah
